UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szEmail,<br/>Your request for creating new password is Accepted.Please use temporary Password for login.<br/><br/>szLink<br/><br/><br/><br/>Kind regards,<br/>Drug Safe Communities</p></p>' WHERE `tbl_email_cms`.`id` = 1;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szName, <br /> <br /> <br /> <br /> <br /> Welcome to Drug Safe Communities!<br /> <br/> <br/> <br/> Please click on the link to login in to Drug Safe Communities : <br/><br/> Link <br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br /> Kind regards,<br /> Drug Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 2;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szName, <br /> <br /> <br /> <br /> <br /> Welcome to Drug Safe Communities !<br /> <br/> <br/> <br/> Please click on the link to login in to Drug Safe Communities : <br/><br/> Link <br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br /> Kind regards,<br /> Drug Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 3;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear Admin, <br /> <br /> <br /> <br /> <br /> szName Send a Request for Quantity,<br /> <br/> <br/> <br/> Here is all the detailed data send by him : <br/><br/> Product Name - szProductCode <br/> Requested Quantity - szQuantity <br/><br/> You can assign Product on clicking this url. <br/> <br/> szHttpsLink <br/> <br /> Kind regards,<br /> Drug Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 4;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szName, <br /> <br /> <br /> <br /> <br /> Welcome to Drug Safe Communities!<br /> <br/> <br/> <br/> Please click on the link to login in to Drug Safe Communities : <br/><br/> Link <br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br /> Kind regards,<br /> Drug Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 5;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szName, <br /> <br /> <br /> <br /> <br /> Welcome to Drug Safe Communities!<br /> <br/> <br/> <br/> Please click on the link to login in to Drug Safe Communities : <br/><br/> Link<br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br /> Kind regards,<br /> Drug Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 6;
UPDATE `tbl_email_cms` SET `sectionDescription` = ' <br/> <br />  Kind regards,<br /> Drug Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 7;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szName, <br /> <br /> <br /> <br /> <br /> Welcome to Drug Safe Communities!<br /> <br/> <br/> <br/> You can login on drugsafe app with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br /> Kind regards,<br /> Drug Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 8;

UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szName, <br /> <br /> <br /> <br /> <br /> Welcome to Drug-Safe Communities!<br /> <br/> <br/> <br/> You can login on drugsafe app with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br /> Kind regards,<br /> Drug-Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 8;
UPDATE `tbl_email_cms` SET `sectionDescription` = ' <br/> <br />  Kind regards,<br /> Drug-Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 7;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szName, <br /> <br /> <br /> <br /> <br /> Welcome to Drug-Safe Communities!<br /> <br/> <br/> <br/> Please click on the link to login in to Drug-Safe Communities : <br/><br/> Link<br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br /> Kind regards,<br /> Drug-Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 6;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szName, <br /> <br /> <br /> <br /> <br /> Welcome to Drug-Safe Communities!<br /> <br/> <br/> <br/> Please click on the link to login in to Drug-Safe Communities : <br/><br/> Link <br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br /> Kind regards,<br /> Drug-Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 5;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear Admin, <br /> <br /> <br /> <br /> <br /> szName Send a Request for Quantity,<br /> <br/> <br/> <br/> Here is all the detailed data send by him : <br/><br/> Product Name - szProductCode <br/> Requested Quantity - szQuantity <br/><br/> You can assign Product on clicking this url. <br/> <br/> szHttpsLink <br/> <br /> Kind regards,<br /> Drug-Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 4;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szName, <br /> <br /> <br /> <br /> <br /> Welcome to Drug-Safe Communities !<br /> <br/> <br/> <br/> Please click on the link to login in to Drug-Safe Communities : <br/><br/> Link <br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br /> Kind regards,<br /> Drug-Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 3;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szName, <br /> <br /> <br /> <br /> <br /> Welcome to Drug-Safe Communities!<br /> <br/> <br/> <br/> Please click on the link to login in to Drug-Safe Communities : <br/><br/> Link <br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br /> Kind regards,<br /> Drug-Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 2;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szEmail,<br/>Your request for creating new password is Accepted.Please use temporary Password for login.<br/><br/>szLink<br/><br/><br/><br/>Kind regards,<br/>Drug-Safe Communities</p></p>' WHERE `tbl_email_cms`.`id` = 1;
ALTER TABLE `ds_orders` ADD `isReceived` TINYINT(1) NOT NULL AFTER `validorder`;

ALTER TABLE `ds_sos` ADD `sign1` TINYINT( 1 ) NOT NULL ,
ADD `sign2` TINYINT( 1 ) NOT NULL ;
ALTER TABLE `ds_coc` ADD `signcoc1` TINYINT( 1 ) NOT NULL DEFAULT '0',
ADD `signcoc2` TINYINT( 1 ) NOT NULL DEFAULT '0',
ADD `signcoc3` TINYINT( 1 ) NOT NULL DEFAULT '0',
ADD `signcoc4` TINYINT( 1 ) NOT NULL DEFAULT '0',
ADD `signcoc5` TINYINT( 1 ) NOT NULL DEFAULT '0',
ADD `signcoc6` TINYINT( 1 ) NOT NULL DEFAULT '0';
INSERT INTO `tbl_email_cms` (`id`, `szFriendlyName`, `sectionTitle`, `subject`, `sectionDescription`, `iActive`, `atCreatedOn`, `atUpdatedOn`) VALUES (NULL, 'Agent/Employee New Password Email', '__NEW_PASSWORD_FOR_AGENT/EMP__', 'Agent/Employee New Password ', '<p>Dear szName,<br/>Your Password has been changed successfully.<br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br /> Kind regards,<br /> Drug-Safe Communities.</p>', '1', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `tbl_email_cms` (`id`, `szFriendlyName`, `sectionTitle`, `subject`, `sectionDescription`, `iActive`, `atCreatedOn`, `atUpdatedOn`) VALUES (NULL, 'Client New Email', '__NEW_EMAIL_FOR_CLIENT__', 'Client New Email', '<p>Dear szName,<br/>Your Email has been changed successfully.<br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> <br/> <br /> Kind regards,<br /> Drug-Safe Communities.</p>', '1', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
ALTER TABLE `ds_doner` ADD `otherdrug` VARCHAR( 255 ) NOT NULL AFTER `drug` ;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szName,<br/>Your Email has been changed successfully.<br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br />ssKind regards,<br /> Drug-Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 10;
INSERT INTO `tbl_email_cms` (`id`, `szFriendlyName`, `sectionTitle`, `subject`, `sectionDescription`, `iActive`, `atCreatedOn`, `atUpdatedOn`) VALUES (NULL, 'Operation Manager New Email', '__NEW_EMAIL_FOR_OPERATION_MANAGER__', 'Operation Manager New Email', '<p>Dear szName,<br/>Your Email has been changed successfully.<br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br />ssKind regards,<br /> Drug-Safe Communities.</p>', '1', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `tbl_email_cms` (`id`, `szFriendlyName`, `sectionTitle`, `subject`, `sectionDescription`, `iActive`, `atCreatedOn`, `atUpdatedOn`) VALUES (NULL, 'Franchisee New Email', '__NEW_EMAIL_FOR_FRANCHISEE__', 'Franchisee New Email', '<p>Dear szName,<br/>Your Email has been changed successfully.<br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br />ssKind regards,<br /> Drug-Safe Communities.</p>', '1', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `tbl_email_cms` (`id`, `szFriendlyName`, `sectionTitle`, `subject`, `sectionDescription`, `iActive`, `atCreatedOn`, `atUpdatedOn`) VALUES (NULL, 'Site New Email', '__NEW_EMAIL_FOR_SITE__', 'Site New Email', '<p>Dear szName,<br/>Your Email has been changed successfully.<br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br />ssKind regards,<br /> Drug-Safe Communities.</p>', '1', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `tbl_email_cms` (`id`, `szFriendlyName`, `sectionTitle`, `subject`, `sectionDescription`, `iActive`, `atCreatedOn`, `atUpdatedOn`) VALUES (NULL, 'AgentNew Email', '__NEW_EMAIL_FOR_AGENT__', 'Agent New Email', '<p>Dear szName,<br/>Your Email has been changed successfully.<br/><br/> You can login with following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br />ssKind regards,<br /> Drug-Safe Communities.</p>', '1', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szName, <br /> <br /> <br /> <br /> <br /> Welcome to Drug-Safe Communities!<br /> <br/> <br/> <br/> You can login on Drug-Safe Communities Mobile Application with the following login details. <br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br /> Kind regards,<br /> Drug-Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 8;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szName, <br /> <br /> <br /> <br /> <br /> Welcome to Drug-Safe Communities!<br /> <br/> <br/> <br/> You can login on Drug-Safe Communities Mobile Application with the following login details.<br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br /> Kind regards,<br /> Drug-Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 6;
UPDATE `tbl_email_cms` SET `sectionDescription` = '<p>Dear szName, <br /> <br /> <br /> <br /> <br /> Welcome to Drug-Safe Communities !<br /> <br/> <br/> <br/> You can login on Drug-Safe Communities Mobile Application with the following login details.<br/> <br/> Email - szEmail <br/> Password - szPassword <br/> <br /> Kind regards,<br /> Drug-Safe Communities.</p>' WHERE `tbl_email_cms`.`id` = 3;
ALTER TABLE `fo_cmnt` DROP `isApproved`;
ALTER TABLE `fo_reply` DROP `isAdminApproved`;
ALTER TABLE `fo_topic` ADD `isApproved` TINYINT(1) NOT NULL AFTER `idUser`;
ALTER TABLE `fo_topic` ADD `isAdminApproved` TINYINT(1) NOT NULL AFTER `isApproved`;
ALTER TABLE `tbl_prospect` CHANGE `abn` `abn` VARCHAR(12) NOT NULL, CHANGE `szZipCode` `szZipCode` VARCHAR(4) NOT NULL, CHANGE `szNoOfSites` `szNoOfSites` VARCHAR(11) NOT NULL;
ALTER TABLE `tbl_product` ADD `supplier` VARCHAR(200) NOT NULL AFTER `szProductCategory`, ADD `min_ord_qty` INT NOT NULL AFTER `supplier`, ADD `model_stk_val` INT NOT NULL AFTER `min_ord_qty`;